services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - SECRET_KEY=qwerqwew4c5w45@##545454
      - DB_NAME=bibi
      - DB_USER=bibi_user
      - DB_PASSWORD=coweorw@#k
      - DB_HOST=db
      - DB_PORT=3306
      - LOAD_SAMPLE_DATA=False
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

  db:
    image: mysql:8.0
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "bibi_user", "-pcoweorw@#k"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    # حذف انتشار پورت به بیرون - فقط برای استفاده داخلی سرویس web
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_DATABASE=bibi
      - MYSQL_USER=bibi_user
      - MYSQL_PASSWORD=coweorw@#k
      - MYSQL_ROOT_PASSWORD=rAdmin12@x
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE  # برای کاهش مشکلات احتمالی عملکرد MySQL

volumes:
  mysql_data: 