# Generated by Django 4.2 on 2025-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_product_options_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'راننده', 'verbose_name_plural': 'رانندگان'},
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ افزودن'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پلاک'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع وسیله نقلیه'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام راننده'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
    ]
