# Generated by Django 4.2 on 2025-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_driver_options_driver_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده'), ('DELIVERED', 'تحویل داده شده'), ('RECEIVED', 'دریافت شده')], default='PENDING', max_length=20),
        ),
    ]
