# Generated by Django 4.2 on 2025-04-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
    ]
