# Generated by Django 4.2 on 2025-04-14 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_driver_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='واحد (قدیمی)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_ref',
            field=models.ForeignKey('workflow.Unit', null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, verbose_name='واحد'),
        ),
    ]
