# Generated by Django 4.2 on 2025-04-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_update_product_unit_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
    ]
