# Generated by Django 4.2 on 2025-04-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_driver_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش'),
        ),
    ]
