# Generated by Django 4.2 on 2025-04-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_order_last_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='حداقل موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'شعبه'), ('WAREHOUSE', 'انباردار'), ('ACCOUNTANT', 'حسابدار'), ('ADMIN', 'Administrator')], default='REQUESTER', max_length=20),
        ),
    ]
